apiVersion: apps/v1
kind: Deployment
metadata:
  name: Takemeok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Takemeok
  template:
    metadata:
      labels:
        app: Takemeok
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: Takemeok
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vless_UUID
          value: "cee88c4f-1d08-461b-9705-8d2bdf2709b7"
        - name: Vless_Path
          value: "$Vless_Path"
        - name: Vmess_UUID
          value: "cee88c4f-1d08-461b-9705-8d2bdf2709b7"
        - name: Vmess_Path
          value: "$Vmess_Path"
        - name: Share_Path
          value: "$Share_Path"
